### ISSUE TITLE
桥接器不能转发系统主题么？

### ISSUE THREAD

**Issue by cosoc** [rmqtt/rmqtt#124]
如题？

**Comment by cosoc** [comment]
> 是 rmqtt-bridge-egress-pulsar 吗，主题放在：user defined properties 里, https://github.com/streamnative/pulsar-rs/blob/master/src/producer.rs#Message::properties

```toml
[[bridges.entries]]
local.topic_filter = "test/+/data"
remote.topic = "test-msg"

[[bridges.entries]]
local.topic_filter = "$SYS/brokers/+/clients/#"
remote.topic = "device-connection-status-msg"
```


[[bridges.entries]]
local.topic_filter = "$SYS/brokers/+/clients/#"
remote.topic = "device-connection-status-msg" 
测了一些，似乎没有转发系统主题
