### ISSUE TITLE
Hook.log doesnt Respect rmqtt.toml's Log configuration

### ISSUE THREAD

**Issue by wheregmis** [rmqtt/rmqtt#165]
Currently i have defined logging to be off.

rmqtt.toml
```toml
# Value: off | file | console | both
log.to = "off"
# Value: trace, debug, info, warn, error
log.level = "info"
log.dir = "/var/log/rmqtt"
log.file = "rmqtt.log"
```

But still the hook.log file under log/rmqtt is taking alot of space
