### ISSUE TITLE
Any plan to use tokio tracing?

### ISSUE THREAD

**Issue by timzaak** [rmqtt/rmqtt#208]
It would be more easy to integrate with OpenTelemetry ecosystem

**Comment by timzaak** [comment]
Here is an simple example to export log via  OpenTelemetry Rust SDK and Tracing.
```rust
// import
use opentelemetry_otlp::{Protocol, WithExportConfig};
use opentelemetry_sdk::Resource;
use tracing_subscriber::layer::SubscriberExt;
use tracing_subscriber::util::SubscriberInitExt;
use tracing::Level;
use tracing_subscriber::{EnvFilter, Layer};


// code
  let log_filter = || EnvFilter::builder()
        .with_default_directive(Level::INFO.into()).from_env_lossy();
if config.otel {
        let resource = Resource::builder().with_service_name("mqtt-server")
            .build();
        let otlp_exporter = opentelemetry_otlp::LogExporter::builder()
            .with_tonic()
            .with_protocol(Protocol::Grpc)
            .with_endpoint("grpc://127.0.0.1:4317")
            .build()?;

        let log_provider = opentelemetry_sdk::logs::SdkLoggerProvider::builder()
            .with_batch_exporter(otlp_exporter)

            .with_resource(resource)
            .build();
        let otel_layer =
            opentelemetry_appender_tracing::layer::OpenTelemetryTracingBridge::new(&log_provider)
            .with_filter(log_filter());

        let fmt_layer = tracing_subscriber::fmt::layer()
            .with_filter(log_filter());
        tracing_subscriber::registry()
            .with(fmt_layer)
            .with(otel_layer)
            .init();
    } else {
        tracing_subscriber::fmt()
            .with_env_filter(log_filter())
            .init();
    }
```


```toml
# deps
tracing = "0.1"
tracing-subscriber ={ version = "0.3",features = ["env-filter"] }
opentelemetry = "0.30"
opentelemetry_sdk = "0.30"
opentelemetry-otlp = {version= "0.30", features = ["grpc-tonic"]}
opentelemetry-appender-tracing = "0.30"

```
